name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 📥 Clone code
      - name: Checkout code
        uses: actions/checkout@v4

      # 🟢 Setup Node 20 (QUAN TRỌNG)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ========================
      # 🟢 BACKEND
      # ========================
      - name: Install backend
        working-directory: backend-crm
        run: npm install

      - name: Start backend
        working-directory: backend-crm
        run: npm start &

      # ========================
      # 🔵 FRONTEND
      # ========================
      - name: Install frontend
        working-directory: frontend-crm
        run: npm install

      - name: Fix permission (IMPORTANT)
        run: chmod -R +x frontend-crm/node_modules/.bin

      - name: Start frontend
        working-directory: frontend-crm
        run: npm run dev &

      # ========================
      # ⏳ WAIT SERVER READY
      # ========================
      - name: Wait for backend
        run: npx wait-on http://localhost:5000

      - name: Wait for frontend
        run: npx wait-on http://localhost:5173

      # ========================
      # 🧪 CYPRESS
      # ========================
      - name: Run Cypress
        working-directory: frontend-crm
        run: npx cypress run